name: MetabComparisonBinaryML
channels:
  - defaults
  - conda-forge
  - cimcb
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - notebook=6.4.7
  - bokeh=1.2.0
  - numpy=1.17.3
  - pandas=1.3.5
  - openpyxl=3.1.2
  - cimcb=2.0.35
  - xlrd=1.2.0
  - keras=2.2.4
  - Jinja2==3.0.3
